### ISSUE TITLE
TLS server: In state connection received CLIENT ALERT: Fatal - Bad Certificate

### ISSUE THREAD

**Issue by Dayton2028** [albirrkarim/mozilla-hubs-installation-detailed#1]
Hello, 

Firstly, I want to say this repo is very good. Thank u very much.

And I met one problem as below:

When I follow below instructions, there will be one error:
"
run command mix phx.gen.cert it will generate key selfsigned_key.pem and certificate selfsigned.pem
rename selfsigned_key.pem to key.pem
rename selfsigned.pem to cert.pem
in reticulum directory move that two file into priv/ folder
"
All other steps I have executed normally, 
But when I run "iex -S mix phx.server", there will be error in the console:

**iex(1)> [info] TLS server: In state connection received CLIENT ALERT: Fatal - Bad Certificate**

Then, when I changed key.pem and cert.pem back to the original dev-ssl.key and dev-ssl.cert, there will not appear the error, and the Reticulum server will run normally.

Do you have the problem? And could you pls help to figure out how to solve the problem? 

Thanks.

**Comment by albirrkarim** [comment]
you don't have to  make  any changes to `dev-ssl.key` and `dev-ssl.cert` 

I have updated the article, please follow instructions from setting up SSL section
https://github.com/albirrkarim/mozilla-hubs-installation-detailed#3-setting-up-https-ssl

**Comment by Dayton2028** [comment]
Hi, AlbirrKarim, thank you very much. 
There is another problem for me with your steps 1.1.4 -- 5:
"Edit the Dialog configuration file turnserver.conf and update the PostgreSQL database connection string to use the coturn schema from the Reticulum database:
psql-userdb="host=hubs.local dbname=ret_dev user=postgres password=postgres options='-c search_path=coturn' connect_timeout=30" "

I didn't find turnserver.conf file with Dialog project, and i only found turnserver.conf under hub-ops directory (./hubs-ops/plans/coturn/habitat/config/turnserver.conf), You mean to modify the file? It will be very appreciated if you can detail the specific steps for updating the configure file and PostgreSQL database. 

Thank you very much.

**Comment by albirrkarim** [comment]
I haven't read about hubs-ops.

I just installed coturn, then setting up turnserver.conf.

But sorry, now i forget about the location of that file

later i will update again the article

**Comment by Dayton2028** [comment]
Thanks a lot,very appreciated

**Comment by Dayton2028** [comment]
Hi, AlbirrKarim, 

Your repo is really good and the servers can run well locally, while,

Have you figured out how to setup the services/servers(retitulum, hubs, spoke, etc) so that others can create and enter room from public IP (like 172.217.163.46:8080)? 

Hub's docs are about setting DNS/Domain/Mail SMTP etc with AWS/DO servers, how to do these things with local deployment? If you find any docs please give me a tip, thank you very much.

**Comment by albirrkarim** [comment]
yes i want that too. Stay tune bro. i will update. thank you for your advice
