### ISSUE TITLE
Unable to create a room, WebSocket connection failed

### ISSUE THREAD

**Issue by cherry-fan** [albirrkarim/mozilla-hubs-installation-detailed#10]
Hi albirrkarim,When someone clicks "Create Room", after few seconds an error appears saying "Unable to create a room, please try again later".
![image](https://user-images.githubusercontent.com/42026148/166943929-2b5456c5-46db-4b2b-a406-f588b1306917.png)
Do you have this problem?

**Comment by albirrkarim** [comment]
no

**Comment by cherry-fan** [comment]
> no
Hi albirrkarim
I have a new problem now. 
![image](https://user-images.githubusercontent.com/42026148/167107910-f2f0c8f5-0d6c-4088-983d-f3f21b2d9b0c.png)

I want to confirm two configurations with you. The dialog service is configured with mediasoup_ LISTEN_ IP and mediagroup_ ANNOUNCED_ Is IP the server's public IP or internal IP? Another is, do we need to modify the hosts file?

**Comment by albirrkarim** [comment]
server public IP

please read carefully

https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/VPS_FOR_HUBS.md#52-dialog

**Comment by cherry-fan** [comment]
> 服务器公网IP
> 
> 请仔细阅读
> 
> https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/VPS_FOR_HUBS.md#52-dialog

When I use the public IP, the dialog can see the error report. mediasoup:ERROR:Channel [pid:398327 RTC::PortManager::Bind() | throwing MediaSoupError: port bind failed due to address not available

。 I suspect it's a firewall problem, but I've configured the corresponding rules. I don't know how to deal with this problem. Do you have any ideas?

**Comment by albirrkarim** [comment]
i will update my repo later, btw now i still installing this hubs on server in china alibaba elastic compute.

i got some error address not available on spoke and hubs admin

stay tune

**Comment by cherry-fan** [comment]
> 我稍后会更新我的仓库，顺便说一句，现在我仍然在中国阿里巴巴弹性计算的服务器上安装这个集线器。
> 
> 我得到了辐条和集线器管理员上不可用的一些错误地址
> 
> 保持关注

OK, OK, thank you very much for the documents you provided

**Comment by albirrkarim** [comment]
https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_SOLVED.md#4-error-listen-eaddrnotavail-address-not-available
