### ISSUE TITLE
System Overview Image Contribution?

### ISSUE THREAD

**Issue by matthewbcool** [albirrkarim/mozilla-hubs-installation-detailed#11]
Very helpful to have the system architecture visualized. https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/docs_img/System_Overview.png

Would you be willing to contribute the image to the docs? https://hubs.mozilla.com/docs/system-overview.html? I will ask for a review from the Hubs engineering team if you do. Thank you!

**Comment by albirrkarim** [comment]
Yes of course.

**Comment by matthewbcool** [comment]
Thank you!

**Comment by albirrkarim** [comment]
i open this pull request @matthewbcool 

https://github.com/MozillaReality/hubs-docs/pull/138
