### ISSUE TITLE
failed to start child: Phoenix.PubSub.PG2Server

### ISSUE THREAD

**Issue by dillfrescott** [albirrkarim/mozilla-hubs-installation-detailed#13]
https://gist.github.com/DillFrescott/80876b759d9db60a7f9a36854dc38315

**Comment by albirrkarim** [comment]
Becareful of erlang and elixir version

https://github.com/albirrkarim/mozilla-hubs-installation-detailed#112-install-requirement

**Comment by jreoka** [comment]
What versions do you recommend?

**Comment by jreoka** [comment]
@albirrkarim Also, Can I skip step 3 if I'm going to use Caddy TLS in front of the stack?

**Comment by albirrkarim** [comment]
> What versions do you recommend?

Please read carefully

https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/VPS_FOR_HUBS.md#elixir-and-erlang-elixir-1123-and-erlang-version-233

**Comment by jreoka** [comment]
Thank you. Ill go ahead and close this issue as it's just a version issue. Feel free to repoen it if you believe it should remain open.
