### ISSUE TITLE
Run dialog Failed.. 

### ISSUE THREAD

**Issue by jbshin-gemiso** [albirrkarim/mozilla-hubs-installation-detailed#15]
![22](https://user-images.githubusercontent.com/75593521/180142465-ae42b01f-f159-4f61-9b7f-c8e56ed5642c.png)

4.2 Run dialog is in progress.

When I type 'npm run start', the error message of the screenshot is displayed and it stops. May I know the cause or solution?

Please help.
have a good day.

**Comment by albirrkarim** [comment]
please info npm and node version

**Comment by jbshin-gemiso** [comment]
The problem has been resolved.

Using 'npm audit fix' after 'npm install' seems to be the problem.
After deleting the Dialog and setting it up again, 'npm install' solved the problem.

The post will be closed.
have a good day!
