### ISSUE TITLE
Missing file admin.html  Error

### ISSUE THREAD

**Issue by jbshin-gemiso** [albirrkarim/mozilla-hubs-installation-detailed#16]
hello.

Thanks to your tutorial, Dialog, Reticulum, Hubs(+admin), and Spoke were successfully running.
However, when I tried to test by connecting to localhost, the following message appeared.

![32](https://user-images.githubusercontent.com/75593521/180431874-b719026b-05e9-471e-8702-82e4bbc33231.png)

And Reticulum keeps getting this error message, I don't know the cause. The error message is as below. Red text appears repeatedly.

![31](https://user-images.githubusercontent.com/75593521/180432129-cdbcb22b-18f5-4332-bb69-d22bfab5c4a1.png)

I'd like to get help with a solution.

First of all, I am using Windows 10+WSL2+Ubuntu20.04 based.

And version information.
elixir : 1.12.3-otp-23
erlang : 23.2.1
nodejs : 16.16.0
npm : 8.14.0

thank you have a good day!
I am always grateful to you for making tutorials.

**Comment by albirrkarim** [comment]
it means reticulum can't find the running hubs admin server

you can check it by accessing it manually.

Hubs admin runs on port 8989

https://localhost:8989

or 

https://example.com:8989

**Comment by jbshin-gemiso** [comment]
Thank you for your advice.
I can connect to https://localhost:8989, but I don't know how to solve the problem yet.

And I have one question.
Isn't the message below repeated in 'reticulum' related to not finding the admin server?

-------------------------------------------------------------------


[error] GenServer #PID<0.899.0> terminating
** (stop) exited in: Task.await(%Task{owner: #PID<0.899.0>, pid: #PID<0.939.0>, ref: #Reference<0.1124556970.450887684.28133>}, 15000)
    ** (EXIT) time out
    (elixir 1.12.3) lib/task.ex:726: Task.await/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ret 1.0.0) lib/ret/page_origin_warmer.ex:79: Ret.PageOriginWarmer.get_aggregated_etag/0
    (ret 1.0.0) lib/ret/page_origin_warmer.ex:37: Ret.PageOriginWarmer.execute/1
    (ret 1.0.0) lib/cachex/warmer.ex:79: Ret.PageOriginWarmer.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :cachex_warmer
State: {{:cache, :page_chunks, %{}, false, {:expiration, nil, 3000, true}, {:fallback, nil, nil}, {:hooks, [], []}, {:limit , nil, Cachex.Policy.LRW, 0.1, []}, [:nonode@nohost], false, [{:warmer, Ret.PageOriginWarmer, nil}]}, nil}
