### ISSUE TITLE
Issues installing erlang 23.0

### ISSUE THREAD

**Issue by dillfrescott** [albirrkarim/mozilla-hubs-installation-detailed#17]
It gives me this:

root@b2a42bf9535c:/# asdf install erlang 23.0
asdf_23.0 is not a kerl-managed Erlang/OTP installation
The asdf_23.0 build has been deleted
Extracting source code
Building Erlang/OTP 23.0 (asdf_23.0), please wait...
APPLICATIONS DISABLED (See: /root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_build_23.0.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_build_23.0.log)
 * wx             : No OpenGL headers found, wx will NOT be usable
 * No GLU headers (glu.h) found, wx will NOT be usable
 * wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_build_23.0.log)
 * documentation  :
 *                  xsltproc is missing.
 *                  fop is missing.
 *                  xmllint is missing.
 *                  The documentation cannot be built.

Build failed.
cc1: some warnings being treated as errors
gmake[4]: *** [x86_64-unknown-linux-gnu/Makefile:171: ../priv/obj/x86_64-unknown-linux-gnu/pkey.o] Error 1
gmake[4]: Leaving directory '/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/lib/crypto/c_src'
gmake[3]: *** [/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/lib/crypto/c_src'
gmake[2]: *** [/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/make/otp_subdir.mk:29: opt] Error 2
gmake[2]: Leaving directory '/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/lib/crypto'
gmake[1]: *** [/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/make/otp_subdir.mk:29: opt] Error 2
gmake[1]: Leaving directory '/root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_src_23.0/lib'
gmake: *** [Makefile:504: libs] Error 2

Please see /root/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0/otp_build_23.0.log for full details.
root@b2a42bf9535c:/#

**Comment by jreoka** [comment]
Any ideas what could be going on?

**Comment by albirrkarim** [comment]
install the requirement 

https://github.com/asdf-vm/asdf-erlang#before-asdf-install

**Comment by jreoka** [comment]
Okay. Thank you

**Comment by jreoka** [comment]
Hmmm, you are supposed to install the packages listed under the `Before asdf install` section correct?

I did that and it threw less errors this time but still failed with the same error...

**Comment by jreoka** [comment]
It could be related to openssl maybe?

**Comment by jreoka** [comment]
I am on Ubuntu 22 is that why? Should I be using 20?

**Comment by albirrkarim** [comment]
keep post the error log here

**Comment by albirrkarim** [comment]
you are in the wrong place to place an issue.

**Comment by jreoka** [comment]
Ah, my bad
