### ISSUE TITLE
Error running mix ecto.create

### ISSUE THREAD

**Issue by dillfrescott** [albirrkarim/mozilla-hubs-installation-detailed#18]
root@e9983a04e5a0:/reticulum# mix ecto.create

20:00:07.329 [error] GenServer #PID<0.455.0> terminating
** (RuntimeError) connect raised UndefinedFunctionError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (crypto 5.0.5) :crypto.hmac/3
    (postgrex 0.15.3) lib/postgrex/scram.ex:52: Postgrex.SCRAM.hash_password/6
    (postgrex 0.15.3) lib/postgrex/scram.ex:26: Postgrex.SCRAM.verify/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:734: Postgrex.Protocol.auth_cont/4
    (postgrex 0.15.3) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.1) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Ret.Repo couldn't be created: killed
root@e9983a04e5a0:/reticulum#
-----------------------------------------------------------------------

I checked to make sure the database is up and listening and checked the dev.exs file and everything is correct.

**Comment by jreoka** [comment]
Figured it out. You have to run `mix deps.update --all` before running ecto.create
