### ISSUE TITLE
Can't find HTML documents when visiting port 4000

### ISSUE THREAD

**Issue by RepSklvska** [albirrkarim/mozilla-hubs-installation-detailed#2]
I followed all the steps by the tutorial (with a little difference), I still got 503 returns when I visit by port 4000 and it shows like:
```Missing file index.html. Please try again.```

The difference is, I set up the server in a virtual Linux server which means it's not running locally, and I kept using host as "hubs.local" for the server's IP address. I visited it by Firefox on Windows, accepted the risk to continue. Can the reason be from those? Or maybe something else?

**Comment by albirrkarim** [comment]
Please star the repo first.

The tutorial is for running locally. 
on `README.md` is for running locally and development. 

for production on the live servers that have public IP and have custom domain check out my other tutorial about [hosting Mozilla hubs projects on vps](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/VPS_FOR_HUBS.md) but this is not complete yet. Stay tune
