### ISSUE TITLE
Error while running reticulum on iMac with command iex -S mix phx.server

### ISSUE THREAD

**Issue by monukbizsoft** [albirrkarim/mozilla-hubs-installation-detailed#25]
Hi

Thanks for giving this tutorial to set up the hub on localhost.

I have followed all steps from the tutorial up to  Step 3 and all steps are working as fine

When I tried Step [4. running](https://github.com/albirrkarim/mozilla-hubs-installation-detailed#4-running)
Then it gives me an error

Please check it below

**== Compilation error in file lib/ret/schema.ex ==
** (CompileError) lib/ret/schema.ex:39: call to local macro is_struct/1 conflicts with imported Kernel.is_struct/1, please rename the local macro or remove the conflicting import
    (elixir 1.14.2) expanding macro: Kernel.and/2
    lib/ret/schema.ex:39: Ret.Schema.is_schema/1
    (elixir 1.14.2) expanding macro: Kernel.and/2
    lib/ret/schema.ex:40: Ret.Schema.is_schema/1
    (elixir 1.14.2) expanding macro: Kernel.Utils.defguard/2
    lib/ret/schema.ex: Ret.Schema.is_schema/1**
Please check the screenshots: 
![Screenshot at Dec 01 12-25-24](https://user-images.githubusercontent.com/119565686/204985979-cee7fb2a-5caf-462c-8003-6a79c33466d5.png)

![error-screenshot](https://user-images.githubusercontent.com/119565686/204984681-9d3181e5-6036-4132-8909-80e94d360119.png)

Installed the version of elixir and erlang per your suggestion
% **asdf current**
elixir          1.14.2          /Users/iMac/Documents/Work/Hub/reticulum/.tool-versions
erlang          25.1.2          /Users/iMac/Documents/Work/Hub/reticulum/.tool-versions

Any help would be appreciated.

**Comment by albirrkarim** [comment]
you install a different version than my tutorial. [see](https://github.com/albirrkarim/mozilla-hubs-installation-detailed#elixir-and-erlang-elixir-112-and-erlang-version-23)

**Comment by monukbizsoft** [comment]
Thanks 

I have fixed this issue

I have one question

is `sudo apt install libpq-dev` command working on Mac?

This is not working on my side
It gives me the below error:

 **sudo apt install libpq-dev**
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

============
Thanks
