### ISSUE TITLE
Images not loaded in your repo

### ISSUE THREAD

**Issue by monukbizsoft** [albirrkarim/mozilla-hubs-installation-detailed#26]
Please check screenshot:

![Screenshot at Dec 14 12-49-02](https://user-images.githubusercontent.com/119565686/207530887-2677dbff-72ad-4e93-b3f8-6dd6c356db3e.png)

**Comment by albirrkarim** [comment]
no, its work in my laptop. try to use VPN

**Comment by monukbizsoft** [comment]
Thanks
