### ISSUE TITLE
Error: JsonWebTokenError: invalid signature

### ISSUE THREAD

**Issue by monukbizsoft** [albirrkarim/mozilla-hubs-installation-detailed#27]
Hi

First Thanks for giving this tutorial And Its working fine.

After Setup it, I am facing error when I am trying to create room.

Please check screenshot: 
![Hubs error](https://user-images.githubusercontent.com/119565686/208870607-87b897e4-a0e3-474b-8a5f-c509e629f3dc.png)

I have updated the Ret.PermsToken in reticulum/config/prod.exs
```
config :ret, Ret.PermsToken,
  # This config value is for local development only.
  perms_key:
"-----BEGIN PRIVATE KEY-----\nMIIEvg***********************TjuAsTj\n-----END PRIVATE KEY-----"
```

Still facing same issue.

Thanks

**Comment by albirrkarim** [comment]
have u do this ? https://github.com/albirrkarim/mozilla-hubs-installation-detailed#122-setting-up-secret-key

**Comment by monukbizsoft** [comment]
Yes I have added it and its working fine on local

But when I pushed it on self hosted server then it gives me error.

**Comment by monukbizsoft** [comment]
This issue was occured due to mis match the public key to private key in Dialog
