### ISSUE TITLE
Missing translation for key: "JWSError JWSInvalidSignature"

### ISSUE THREAD

**Issue by monukbizsoft** [albirrkarim/mozilla-hubs-installation-detailed#28]
Hi 

Thanks for giving this tutorial first and it is best for beginner developer.

I've almost got it setup on a self hosted server with ubuntu 20.04.

After setup this, I am facing only one error when I am trying to access admin menu in backend

spoke, hub frontend and everything else is working fine

Please check screenshot:
![Screenshot at Dec 28 19-07-01](https://user-images.githubusercontent.com/119565686/209821682-fe862c0e-34fc-4c5f-9fa5-e616e036a93c.png)

That is Missing translation for key: "JWSError JWSInvalidSignature".

I have followed you tutorial all steps.

I am trying to fix this from last 3 days and still I can't solve it as I am a beginner developer.

Can someone help me to tell what is missing in the setup of mozilla hub.

Thanks

**Comment by albirrkarim** [comment]
Hmm, btw I'm not in this field for now. (metaverse thing). i move my focus since the pandemic disappear and the META stock s fell.

the metaverse demand is dying (for now).

**Comment by monukbizsoft** [comment]
Okay Thanks

**Comment by eclipse-reality-steven** [comment]
@monukbizsoft I did figure this out, you need to re-run the command here locally and dump it to your where your postgrest service is running. https://github.com/mozilla/hubs-ops/wiki/Running-PostgREST-locally

It should get you back up and running

**Comment by monukbizsoft** [comment]
Hi 

I have followed the step number [4.5](https://github.com/albirrkarim/mozilla-hubs-installation-detailed#45-run-postgrest-server) from your tutorial and now it is working fine

I have reinstalled and configured postgres and now it is working fine.

I have missed "**@**" while configuring postgres on local system.

Thanks again
