### ISSUE TITLE
hubs.link proxy doesn't work

### ISSUE THREAD

**Issue by metascript-cloud** [albirrkarim/mozilla-hubs-installation-detailed#29]
How can we fix the shortlinks in NGINX? I have already set up SSL for the shortlink and got it connecting to the same server that hosts the hubs domain. My issue is I am having problems writing the nginx rule that redirects the shortlink to **fulldomain.com/link/xyz**

According to what I know I tried this but its not giving the expected results.

`server {
    server_name short.link
    location / {
        return 301 https://fulldomain.com/link/$1;
    }
    ...
}`

Would appreciate any help on this issue.

Thanks

**Comment by albirrkarim** [comment]
try to search google or chat GPT about `how to set multiple domain nginx`

**Comment by metascript-cloud** [comment]
Hey thanks for replying I know how to do that problem I am facing I am having issue understanding which port it needs to redirect. 

This code actually works but it taking me to NGINX page, which would be the host to use?

```
server {
    server_name shortlink.link;
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/shortlink.link/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shortlink.link/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location / {
        rewrite ^/([0-9]+)$ https://fulldown.com/link/$1 permanent;
    }
}
```

**Comment by metascript-cloud** [comment]
What I am noticing is everything will work fine but just the link in the browser won't change, I suspect somewhere else in the NGINX is already handling this?

**Comment by albirrkarim** [comment]
can i see the actual url ?

**Comment by albirrkarim** [comment]
have you see the access and error log of nginx?

**Comment by metascript-cloud** [comment]
Hey! Good news manage to get it working after giving it another try. 

I think what I wasn't doing before was explicitly setting the server_name in each block, now its working good.

For anyone interested in solution its this:

```
server {
    server_name short.link;
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location / {
        return 301 $scheme://longlink.com/link/$1;
    }
}
```

Also another side note thanks so much for the guide I don't know how it would have been possible to set this up otherwise!

**Comment by albirrkarim** [comment]
btw if your code have multiple line and you want to embed on github markdown use ``` (triple `)
