### ISSUE TITLE
 Is the admin menu working at your place?

### ISSUE THREAD

**Issue by kouzzy** [albirrkarim/mozilla-hubs-installation-detailed#3]
Hi, albirrkarim.
Thanks to your documentation, some issues have been resolved and paved the way. 
I am very grateful to you. by the way,...
Is the admin menu working at your place?
I can't import scenes and avatars.
The other menu says "server communication error", is this the same for you?

Thank you as always.

**Comment by albirrkarim** [comment]
yes, i have that problem too. [see](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_UNSOLVED.md)

i think later i will make some backend service for that.

**Comment by justincolangelo** [comment]
We've been discussing over time in the Hubs discord this issue. As you mention in your setup document the problems that still exist are that Mozilla has an ITA service that is private code. Based on the minified JS for the ITA service it looks like that handles the deploy/undeploy/config updates for the biome habitat ring on the servers. It looks like it is a node server. Have you started to develop your own? I guess you commented about this 2 days ago so probably not yet... 

Mainly the issue we see is that when updating the admin server settings (on the server) we get a permission denied error related to `bio config apply ...`. Running locally and trying to point at a remote ITA server did not seem to help the local admin issues either. It sounds like a custom solution is necessary. How can I help?

**Comment by kouzzy** [comment]
Thank you for your comment. Roughly I understand the situation.
The immediate purpose is a communication test with "LOCAL Mozilla hubs". I think that it is possible only with the hubs main function.
If the scene and avatar can be reflected, it is possible, so I will try it, although it is limited.
But hopefully someday I can use the "admin menu".
thank you. May you be happy.

**Comment by albirrkarim** [comment]
Solved [502 error solved](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_SOLVED.md#--502-server-communication-error-in-hubs-admin-like-this-issue)

also see [problem i still faced](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_UNSOLVED.md#what-is-localhost6000)
