### ISSUE TITLE
I dont know what it is "scene_listings"

### ISSUE THREAD

**Issue by Fi1osof** [albirrkarim/mozilla-hubs-installation-detailed#30]
This is now issue, just explanation for figma file.
![image](https://user-images.githubusercontent.com/2550668/220700599-f14d5848-2568-45c7-b77c-14cc3a119a38.png)

Hub table have two columns (scene_id and scene_listing_id). If you have scene_listing_id=null and filled scene_id, when you update project via Spoke and publish scene, hub will get alst version of them. But if you approve scene for hub via Admin panel (and scene_listing_id filled), hub will use only specified version of this scene. Thus you have the opportunity to use one project and many scene versions for different rooms (hubs).

**Comment by albirrkarim** [comment]
thanks for the info
