### ISSUE TITLE
Certification added to Ubuntu, but browser still shows insecure

### ISSUE THREAD

**Issue by hubback** [albirrkarim/mozilla-hubs-installation-detailed#36]
Hi
I followed tutorial 3.1 and successfully added a cert to the system

![圖片](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/assets/156076798/54c6dfc0-e850-49ce-bde5-4c0fd6e1e77f)

However, firefox still shows insecure and JWT errors when entering the scene. Any solution? Thanks

![圖片](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/assets/156076798/d0eb29dc-8ed6-4789-a220-280c7c5a6aa3)

**Comment by albirrkarim** [comment]
why you don't follow the official method? https://hubs.mozilla.com/labs/welcoming-community-edition/

btw I'm not playing in the Mozilla hubs anymore
