### ISSUE TITLE
Failed to load resource: the server responded with a status of 503 ()

### ISSUE THREAD

**Issue by lhtvineettiwari** [albirrkarim/mozilla-hubs-installation-detailed#6]
Hi albirrkarim, We have set up hubs, dialog, spoke and reticulum locally successfully but when access https://localhost:4000/ then facing missing file schema.toml file on browser console

![image](https://user-images.githubusercontent.com/91462759/162165906-68b8cff9-6e46-4f8f-bb6a-fce5c20ba8b5.png)

and before this 503 error we are getting this one 
![image](https://user-images.githubusercontent.com/91462759/162166531-2b41759b-99df-4252-b01b-c7225e64b597.png)

Please Look into this and Thank you.

**Comment by albirrkarim** [comment]
Based on your picture number one. I think you forget to run hubs admin.

**Comment by lhtvineettiwari** [comment]
I have run the hub admin, but still it is giving me this error.

**Comment by albirrkarim** [comment]
can you open https://localhost:8989 ?

**Comment by lhtvineettiwari** [comment]
Yes, [https://localhost:8989/] this is opening but it is showing

![image](https://user-images.githubusercontent.com/91462759/165564616-2512d806-a1cc-4c7e-bd04-464f28801f5e.png)

and for 4000

![image](https://user-images.githubusercontent.com/91462759/165564736-9b2367a2-8760-41ec-871b-00df53f6143e.png)

and also the reticulum server is also throwing this error:

![image](https://user-images.githubusercontent.com/91462759/165564863-5a41bd3d-d81d-4527-baa0-e9ce03084f2c.png)


Kindly have a look, trying to resolve this from a long time.

**Comment by albirrkarim** [comment]
is in hubs admin terminal like this?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/29292018/165654373-e878f5d1-7199-4106-8ae3-4d8eea6cbc6b.png">

**Comment by lhtvineettiwari** [comment]
hubs admin terminal:
 
![image](https://user-images.githubusercontent.com/91462759/165658836-f56becab-d1a8-4dd8-99d3-d9a7ba1a2481.png)
![image](https://user-images.githubusercontent.com/91462759/165658903-88bea014-3e0a-4640-9339-cf9dbaba83d0.png)

**Comment by albirrkarim** [comment]
> hubs admin terminal:
> 
> ![image](https://user-images.githubusercontent.com/91462759/165658836-f56becab-d1a8-4dd8-99d3-d9a7ba1a2481.png) ![image](https://user-images.githubusercontent.com/91462759/165658903-88bea014-3e0a-4640-9339-cf9dbaba83d0.png)

You forget to replace the URL base..
See on the first image `Project is running at hubs.local` 


We are not using `hubs.local` domain. we use `localhost` 

Of course the reticulum on `localhost` can't find the hubs admin
