### ISSUE TITLE
address not available

### ISSUE THREAD

**Issue by cherry-fan** [albirrkarim/mozilla-hubs-installation-detailed#7]
Hi albirrkarim,
According to your process, hubs can be started normally, but hub admin and spoke cannot be started. The following error is reported

node:events:504

throw er; // Unhandled 'error' event

^

error: listen EADDRNOTAVAIL: address not available ******:8989

at Server. setupListenHandle [as _listen2] (node:net:1313:21)

at listenInCluster (node:net:1378:12)

at GetAddrInfoReqWrap. doListen [as callback] (node:net:1516:7)

at GetAddrInfoReqWrap. onlookup [as oncomplete] (node:dns:73:8)

Emitted 'error' event on Server instance at:

at emitErrorNT (node:net:1357:8)

at processTicksAndRejections (node:internal/process/task_queues:83:21) {

code: 'EADDRNOTAVAIL',

errno: -99,

syscall: 'listen',

address: '********',

port: 8989

}

I don't know about the front end. Did you encounter this problem during deployment? Please help me have a look

**Comment by albirrkarim** [comment]
Have you run entire hubs on local successfully ?

**Comment by cherry-fan** [comment]
> Hi albirrkarim,
I have successfully run it locally. For that problem, I have modified the host file and solved it. Now I have a new problem. When I open the home page to create a room, I will immediately jump to / sign? sign_ in&sign_ in_ Destination = admin, when I enter the mailbox, but I don't receive the verification email, do I need to configure the mailbox separately? Do you have this problem?

**Comment by albirrkarim** [comment]
> > Hi albirrkarim,
> > I have successfully run it locally. For that problem, I have modified the host file and solved it. Now I have a new problem. When I open the home page to create a room, I will immediately jump to / sign? sign_ in&sign_ in_ Destination = admin, when I enter the mailbox, but I don't receive the verification email, do I need to configure the mailbox separately? Do you have this problem?

[See](https://github.com/mozilla/reticulum#5-logging-in)
