### ISSUE TITLE
extra settings are required

### ISSUE THREAD

**Issue by danielwang24139212** [albirrkarim/mozilla-hubs-installation-detailed#8]
Hi, 
I tried to install the hubs project on the self-hosted project.
Almost done, but could not see the landing page of hubs, hubs_admin, and spoke projects.
I think you probably modified /etc/hosts file regarding your new domain.
Let me know if you did that, then how?
Thanks.

**Comment by albirrkarim** [comment]
Have you run the whole hub on local? with success (no issue)?

**Comment by danielwang24139212** [comment]
Thanks for your reply.

**Comment by danielwang24139212** [comment]
I successfully deployed it on localhost.
Can you share your live server URL so that I can visit it?

**Comment by danielwang24139212** [comment]
And your Nginx config file says that all HTTP requests are redirected to port 4000(reticulum) but it seems hubs, hubs_admin, and spoke could not work due to it.
spoke load entry point js file on index.html. Below is the URL of that file.
www.example.com:9090/assets/js/XXXx-xXXXX.js
But you configured all requests to be redirected to 4000 port.
So how could the entry point of spoke run?

Please explain this.
Thanks.

**Comment by danielwang24139212** [comment]
I am a little urgent now.
If you have a chance, let me know your skype id via email.
Here is my email address.

danielwang24139212@gmail.com

Thanks.

**Comment by albirrkarim** [comment]
> And your Nginx config file says that all HTTP requests are redirected to port 4000(reticulum) but it seems hubs, hubs_admin, and spoke could not work due to it. spoke load entry point js file on index.html. Below is the URL of that file. [www.example.com:9090/assets/js/XXXx-xXXXX.js](http://www.example.com:9090/assets/js/XXXx-xXXXX.js) But you configured all requests to be redirected to 4000 port. So how could the entry point of spoke run?
> 
> Please explain this. Thanks.

Not like that.

My Nginx config says is.

443 -> pass to 4000

8989 still 8989
9090 still 9090
and another port is still same


**Proxy pass is only for reticulum**

If you type `example.com` by default your browser will get from port 443 which is https. but the reticulum is in 4000

User must go to `example.com:4000` to get the reticulum

But we don't want that. we want if user type `example.com` the user will get same result. as they visit `example.com:4000`

So we need proxy pass it. [see](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/VPS_FOR_HUBS.md#7-setting-up-nginx)

**Comment by albirrkarim** [comment]
> I am a little urgent now. If you have a chance, let me know your skype id via email. Here is my email address.
> 
> [danielwang24139212@gmail.com](mailto:danielwang24139212@gmail.com)
> 
> Thanks.

I'm sorry for now I'm still busy with my projects

**Comment by danielwang24139212** [comment]
Okay.
What hosting service do you use?
My one is on AWS, and I think inbound settings for ports 8989, 9090, and 8080 should be opened, right?
Not just for "sudo uwf allow ....".

**Comment by albirrkarim** [comment]
> Okay. What hosting service do you use? My one is on AWS, and I think inbound settings for ports 8989, 9090, and 8080 should be opened, right? Not just for "sudo uwf allow ....".

Yes just open it.

**Comment by danielwang24139212** [comment]
Hi, albirrkarim.
One question, can you get the landing page of the spoke project if you visit https://example.com:9090 on your server?
From your Nginx configuration, it's not possible, right?
So, I think the reticulum also could not access to spoke entry js file.

If you have successfully hosted the server please provide the url.
Thanks.

**Comment by albirrkarim** [comment]
> danielwang24139212@gmail.com

I have send the link to your email [danielwang24139212@gmail.com](mailto:danielwang24139212@gmail.com)

**Comment by danielwang24139212** [comment]
Thanks. let me check it.

**Comment by danielwang24139212** [comment]
Thank you very much.
This is an excellent post.
