### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by cherry-fan** [albirrkarim/mozilla-hubs-installation-detailed#9]
Hi albirrkarim, thank you for your documentation! excuse me, have you found the problem about hub admin 502

**Comment by kouzzy** [comment]
hi, cherry-fan.
Did the "login not receive link" issue go away?

**Comment by albirrkarim** [comment]
For local login [see](https://github.com/mozilla/reticulum#5-logging-in)

For production server i just bypass it in backend by edit the elixir code.

And on the front end i use google sign in

So my app just have security layer on the front end 😹 not in backend hahaha 

I think on production server you should set SMTP config on reticulum, so it will work

**Comment by albirrkarim** [comment]
> Hi albirrkarim, thank you for your documentation! excuse me, have you found the problem about hub admin 502

Yes
https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_UNSOLVED.md

**Comment by cherry-fan** [comment]
> 嗨，樱桃迷。 “登录未收到链接”问题是否消失了？

still exist

**Comment by cherry-fan** [comment]
> > Hi albirrkarim, thank you for your documentation! excuse me, have you found the problem about hub admin 502
> 
> Yes https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/PROBLEM_UNSOLVED.md

ok，thank you very much
